### ISSUE TITLE
[Node] client hook with sandglass service

### ISSUE THREAD

**Issue by c1tt1** [celrenheit/sandglass-client#1]
Since sandglass can be installed as a service with Homewbrew, I was wondering if it can be exposed kind like how RabbitMQ is exposed through http. 

Here I am making a Nodejs example but the concept can be applied for different languages:

Here is how to hook the Node `amqplib` client library to the rabbitMQ service:

```js
let amqp = require('amqplib/callback_api');
amqp.connect('amqp://localhost', function(err, conn) {});
``` 
or
```js
let open = require('amqplib').connect('amqp://localhost');
```

This is the same scenario for other clients. I hope to have made my question clear.

**Comment by celrenheit** [comment]
Sandglass is exposed through http but clients should you use the grpc protocol.
If you are not familiar with grpc, I invite you to check [this out](https://grpc.io/docs/tutorials/basic/node.html).
Effectively, a client would be a wrapper around the javascript code already generated. You find it here: https://github.com/celrenheit/sandglass-grpc/tree/master/node.
I'll try to publish to generated code to npm.

**Comment by c1tt1** [comment]
Thanks for explaining, that's really helpful. I'm familiar with rpc but never used grpc so it would be very interesting. And yes, publishing the generated code would be a good idea, and it could part of client as a dependency. 
I'm closing this issue as it's solved.

**Comment by celrenheit** [comment]
The generated is already published [here](https://github.com/celrenheit/sandglass-grpc/tree/master/node) but I noticed that there is an issue with code generated for node.js (some [imports](https://github.com/celrenheit/sandglass-grpc/blob/master/node/sandglass_grpc_pb.js#L7) that should not be imported).
I'll check this out this evening.

**Comment by celrenheit** [comment]
I've fixed the node.js base grpc code.
It's the dynamic version not the static anymore. It's a bit hacky but it will do the job for now.
```shell
npm install grpc @sandglass/grpc
```

and the base code, this should list all the partitions:

```js
var sgproto = require('@sandglass/grpc');
var grpc = require('grpc')
var client = new sgproto.BrokerService(':7170', grpc.credentials.createInsecure());

client.getTopic({
    name: "emails"
}, function(err, resp) {
    if (err) {
        console.log(err)
        return;
    }
    console.log(resp)
})
```
(make sure to create the `emails` topic)

I've made this base available here: https://github.com/celrenheit/sandglass-client/tree/master/node

**Comment by c1tt1** [comment]
I did notice the unused imports, but sounds cool.

**Comment by c1tt1** [comment]
sorry I have re-opened this again, but was thinking about doing the node client methods async.
for example the following for creating a topic:

```js
  async createTopic(params) {
    return new Promise((resolve, reject) => {

      client.CreateTopic(params, (err, resp) => {
        if (err) return reject(err)
        return resolve(resp)
      })
    })
  }
````

what are your thoughts?

**Comment by celrenheit** [comment]
Sounds good to me
